name: COBOL Check Automation

on:
  push:
    branches: [ main ]

jobs:
  cobol-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
    - name: Setup Mainframe Environment and Upload COBOL Check
      env:
        ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
        ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
      run: |
        # Here we'll add our commands to run cobolcheck
        chmod +x .github/scripts/zowe_operations.sh
        .github/scripts/zowe_operations.sh
        echo "Running COBOL Check"
        # Add actual cobolcheck commands here
    - name: Run COBOL Check on Mainframe
      env:
        ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
        ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
      run: |
         chmod +x .github/scripts/mainframe_operations.sh
         .github/scripts/mainframe_operations.sh



































        













































































































        
